{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-openfire-admin
  labels:
    app: openfire
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: admin
  to:
    kind: Service
    name: {{ .Release.Name }}-openfire
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
