apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-openfire
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openfire.labels" . | nindent 4 }}
automountServiceAccountToken: false
