namespace:
  name: openfire-build
  create: true

git:
  url: https://github.com/mkoese/openfire-oci.git
  revision: main

image:
  name: image-registry.openshift-image-registry.svc:5000/openfire-build/openfire-oci
  tag: "5.0.3"

openfire:
  version: "5.0.3"
  downloadUrl: https://github.com/igniterealtime/Openfire/releases/download/v5.0.3/openfire_5_0_3.tar.gz

workspace:
  storageSize: 1Gi

plugins:
  - name: userstatus
    url: https://igniterealtime.org/projects/openfire/plugins/1.3.0/userstatus.jar

pipelineRun:
  # Set to true to create a PipelineRun (triggers an immediate build)
  enabled: false
