namespace:
  name: openfire-build
  create: true

git:
  url: https://github.com/mkoese/openfire-oci.git
  revision: main

image:
  repository: image-registry.openshift-image-registry.svc:5000
  name: openfire-build/openfire-oci
  # tag defaults to openfire.version if not set

openfire:
  version: "5.0.3"
  downloadBaseUrl: "https://github.com/igniterealtime/Openfire/releases/download"

workspace:
  storageSize: 1Gi

plugins:
  - name: userstatus
    url: https://igniterealtime.org/projects/openfire/plugins/1.3.0/userstatus.jar

pipelineRun:
  # Set to true to create a PipelineRun (triggers an immediate build)
  enabled: false
