{{- if .Values.pipelineRun.enabled }}
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: openfire-build-
spec:
  pipelineRef:
    name: openfire-build
  params:
    - name: git-url
      value: {{ .Values.git.url | quote }}
    - name: git-revision
      value: {{ .Values.git.revision | quote }}
    - name: image-name
      value: {{ .Values.image.name | quote }}
    - name: image-tag
      value: {{ .Values.image.tag | quote }}
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.workspace.storageSize }}
    - name: dockerconfig
      secret:
        secretName: {{ .Values.registry.secretName }}
{{- end }}
